server:
  port: 8080

spring:
  application:
    name: framework
  datasource:
    url: jdbc:mysql://192.168.1.3:3306/zgjm?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: ly19980527
    driver-class-name: com.mysql.jdbc.Driver
  elasticsearch:
    rest:
      uris: 110.40.240.221:9200
      username: elastic
      password: ly19980527
